Webuntis\Models\Classes:
    repositoryClass: null
    fields:
        name:
            type: string
            apiName: name
        fullName:
            type: string
            apiName: longName
