Webuntis\Models\Exams:
    repositoryClass: Webuntis\Repositories\ExamsRepository
    fields:
        startDate:
            type: date
            api:
                name: startDate
        endDate:
            type: date
            api:
                name: endDate
        classes:
            type: array
            api:
                name: classes
        teachers:
            type: array
            api:
                name: teachers
        students:
            type: array
            api:
                name: students
        subject:
            type: array
            api:
                name: subject

