Webuntis\Models\Exams:
    repositoryClass: Webuntis\Repositories\ExamsRepository
    fields:
        startDate:
            type: date
            apiName: startDate
        endDate:
            type: date
            apiName: endDate
        classes:
            type: array
            apiName: classes
        teachers:
            type: array
            apiName: teachers
        students:
            type: array
            apiName: students
        subject:
            type: array
            apiName: subject

