Webuntis\Models\Holidays:
    repositoryClass: null
    fields:
        startDate:
            type: date
            api:
                name: startDate
        endDate:
            type: date
            api:
                name: startDate
        fullName:
            type: string
            api:
                name: longName
        name:
            type: string
            api:
                name: name
