Webuntis\Models\Period:
    repositoryClass: Webuntis\Repositories\PeriodRepository
    fields:
        startTime:
            type: date
            api:
                name: startTime
        endTime:
            type: date
            api:
                name: endTime
        classes:
            type: array
            api:
                name: kl
        teachers:
            type: array
            api:
                name: te
        subjects:
            type: array
            api:
                name: su
        rooms:
            type: array
            api:
                name: ro
        code:
            type: string
            api:
                name: code
        type:
            type: string
            api:
                name: lstype
