Webuntis\Models\Schoolyears:
    repositoryClass: Webuntis\Repositories\SchoolyearsRepository
    fields:
        startDate:
            type: date
            api:
                name: startDate
        endDate:
            type: date
            api:
                name: endDate
        name:
            type: string
            api:
                name: name
