Webuntis\Models\Substitutions:
    repositoryClass: Webuntis\Repositories\SubstitutionsRepository
    fields:
        startTime:
            type: date
            api:
                name: startTime
        endTime:
            type: date
            api:
                name: endTime
        classes:
            type: array
            api:
                name: kl
        teachers:
            type: array
            api:
                name: te
        subjects:
            type: array
            api:
                name: su
        rooms:
            type: array
            api:
                name: ro
        lesson:
            type: string
            api:
                name: lsid
        type:
            type: string
            api:
                name: type
        text:
            type: string
            api:
                name: text
