Webuntis\Models\Teachers:
    repositoryClass: null
    fields:
        name:
            type: string
            apiName: name
        firstName:
            type: string
            apiName: foreName
        lastName:
            type: string
            apiName: longName